"""empty message

Revision ID: 3eb39c2e9f71
Revises: b5ad4eeada06
Create Date: 2026-08-28 19:45:52.405056

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '3eb39c2e9f71'
down_revision = 'b5ad4eeada06'
branch_labels = None
depends_on = None


def upgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  with op.batch_alter_table('app', schema=None) as batch_op:
    batch_op.add_column(sa.Column('status', sa.String(length=255), nullable=False))

  # ### end Alembic commands ###


def downgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  with op.batch_alter_table('app', schema=None) as batch_op:
    batch_op.drop_column('status')

  # ### end Alembic commands ###
